### ISSUE TITLE
error message of "File not found at path: \"

### ISSUE THREAD

**Issue by tanzhenchao** [owncloud/files_external_ftp#46]
How to fix error below?

`{"reqId":"ZgmH0noCXCsiTytETzMT","level":3,"time":"2019-05-24T03:09:04+00:00","remoteAddr":"10.168.0.165","user":"will","app":"files_external","method":"PUT","url":"/index.php/apps/files_external/globalstorages/8","message":"Exception: {\"Exception\":\"League\Flysystem\FileNotFoundException\",\"Message\":\"File not found at path: \",\"Code\":0,\"Trace\":\"#0 /var/www/owncloud/lib/composer/league/flysystem/src/Filesystem.php(353): League\Flysystem\Filesystem->assertPresent('')\\n#1 /var/www/owncloud/lib/composer/league/flysystem/src/Plugin/GetWithMetadata.php(33): League\Flysystem\Filesystem->getMetadata('')\\n#2 [internal function]: League\Flysystem\Plugin\GetWithMetadata->handle('', Array)\\n#3 /var/www/owncloud/lib/composer/league/flysystem/src/Plugin/PluggableTrait.php(72): call_user_func_array(Array, Array)\\n#4 /var/www/owncloud/lib/composer/league/flysystem/src/Plugin/PluggableTrait.php(88): League\Flysystem\Filesystem->invokePlugin('getWithMetadata', Array, Object(League\Flysystem\Filesystem))\\n#5 /var/www/owncloud/apps/files_external_ftp/lib/Storage/FTP.php(145): League\Flysystem\Filesystem->__call('getWithMetadata', Array)\\n#6 /var/www/owncloud/lib/private/Files/Storage/Common.php(440): OCA\Files_external_ftp\Storage\FTP->stat('')\\n#7 /var/www/owncloud/lib/private/Files/External/LegacyUtil.php(205): OC\Files\Storage\Common->test(false, true)\\n#8 /var/www/owncloud/apps/files_external/lib/Controller/StoragesController.php(254): OC\Files\External\LegacyUtil::getBackendStatus('\\OCA\\Files_exte...', Array, false, true)\\n#9 /var/www/owncloud/apps/files_external/lib/Controller/GlobalStoragesController.php(186): OCA\Files_External\Controller\StoragesController->updateStorageStatus(Object(OC\Files\External\StorageConfig), true)\\n#10 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(153): OCA\Files_External\Controller\GlobalStoragesController->update(8, 'FTP(Fly)', 'ftp', 'builtin::builti...', Array, Array, Array, Array, 100, true)\\n#11 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(85): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_External\Controller\GlobalStoragesController), 'update')\\n#12 /var/www/owncloud/lib/private/AppFramework/App.php(100): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_External\Controller\GlobalStoragesController), 'update')\\n#13 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('OCA\\Files_Exter...', 'update', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\\n#14 /var/www/owncloud/lib/private/Route/Router.php(342): OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)\\n#15 /var/www/owncloud/lib/base.php(909): OC\Route\Router->match('/apps/files_ext...')\\n#16 /var/www/owncloud/index.php(54): OC::handleRequest()\\n#17 {main}\",\"File\":\"/var/www/owncloud/lib/composer/league/flysystem/src/Filesystem.php\",\"Line\":388}"}`

**Comment by ChristophorusReyhan** [comment]
I get the same error, still no answer
